version: '3'
services:
  api:
    container_name: api
    image: api
    build: .
    restart: always
    command: bash -c "npm run start"
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}
  web:
    container_name: web
    image: nginx:1.23-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro
      - ~/html:/var/www/html:ro
      - ~/certbot/www/:/var/www/certbot/:ro
      - ~/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - api