version: '3'
services:
  api:
    container_name: api
    image: api
    build: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}